### ISSUE TITLE
The non-blocking script loader pattern

### ISSUE THREAD

**Issue by bishopZ** [bishopZ/Frame.js#39]
http://calendar.perfplanet.com/2012/the-non-blocking-script-loader-pattern/

Some good ideas here.

**Comment by bishopZ** [comment]
http://webification.com/12-javascript-loaders-to-speed-up-your-web-applications

**Comment by jwaltonmedia** [comment]
hella' good article.  Thanks for the 'add'.

**Comment by bishopZ** [comment]
Fixed in version 2.0
